apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\apps\kompose.exe convert -f react-express-mongodb\compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
