apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\apps\kompose.exe convert -f react-express-mongodb\compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\apps\kompose.exe convert -f react-express-mongodb\compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/react-express-mongodb-react-express: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: frontend
          name: frontend
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /usr/src/app
              name: frontend-claim0
            - mountPath: /usr/src/app/node_modules
              name: frontend-claim1
          command:
            - /bin/sh
            - -c
            - |
              cp -a '/usr/src/app_image/.' '/usr/src/app';
              rm -r ../app_image;
              npm start;
      restartPolicy: Always
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
        - name: frontend-claim1
          persistentVolumeClaim:
            claimName: frontend-claim1
status: {}
