apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\apps\kompose.exe convert -f react-express-mongodb\compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\apps\kompose.exe convert -f react-express-mongodb\compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/react-express-mongodb-express-mongo: "true"
        io.kompose.network/react-express-mongodb-react-express: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: local/backend:v1.6
          name: backend
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: backend-claim0
          volumeMounts:
            - mountPath: /usr/src/app/node_modules
              name: backend-claim1
          command:
            - /bin/sh
            - -c
            - |
              cp -a '/usr/src/app_image/.' '/usr/src/app';
              rm -r ../app_image;
              npm run dev;
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
        - name: backend-claim1
          persistentVolumeClaim:
            claimName: backend-claim1
status: {}
